-- ================================================================================
--   postgres SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   postgres
--   Generated at:      Fri Jan  9 21:15:00 2009
--   Input Files:       pgdia.dia
-- 
-- ================================================================================



-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------



-- Generated Permissions Drops
-- --------------------------------------------------------------------




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------



-- Generated SQL Schema
-- --------------------------------------------------------------------


-- users
create table users (
  id                        serial not null,
  is_blocked                bool default false not null,
  created                   timestamp default now() not null,
  login                     text not null,
  password                  text not null,
  name                      text not null,
  email                     text not null,
  constraint users_pkey primary key (id)
) ;

-- posts
create table posts (
  id                        serial not null,
  user_id                   int not null,
  created                   timestamp default now() not null,
  updated                   timestamp,
  title                     text not null,
  body                      text not null,
  tags                      text[],
  constraint posts_pkey primary key (id)
) ;

-- post_categories
create table post_categories (
  id                        serial not null,
  name                      text not null,
  constraint post_categories_pkey primary key (id)
) ;

-- posts_in_categories
create table posts_in_categories (
  category_id               int not null,
  post_id                   int not null,
  constraint posts_in_categories_pkey primary key (category_id,post_id)
) ;






-- Generated SQL Views
-- --------------------------------------------------------------------



-- Special statements for postgresql:post databases
create index i_posts_tags on posts using gin(tags);


-- Generated Permissions
-- --------------------------------------------------------------------



-- Generated SQL Insert statements
-- --------------------------------------------------------------------


-- inserts for users (login, password, name, email)
insert into users (login, password, name, email) values ( 'admin', 'blah', 'Admin', 'root@localhost' ) ;


-- Generated SQL Constraints
-- --------------------------------------------------------------------

create unique index ui_users_login on users  (login) ;
create unique index ui_categories_name on post_categories  (name) ;
alter table posts add constraint fk_users_posts_post_id
  foreign key (user_id)
  references users (id) on delete cascade ;
alter table posts_in_categories add constraint fk_post_categories_posts_in_categories
  foreign key (post_id)
  references post_categories (id)  ;
alter table posts_in_categories add constraint fk_posts_posts_in_categories
  foreign key (post_id)
  references posts (id) on delete cascade ;

